image: docker:git
services:
    - docker:dind

stages:
  - test
  - build
  - deploy

teste-app:
  stage: test
  # Imagem do dockerfile FROM
  image: python:3.9.10-slim-bullseye
  services:
      - docker:dind
  # Execução do Dockerfile RUN    
  script:
      - apt update && apt install -y python3-mysqldb libmariadb-dev gcc
      - pip install -r requirements.txt
      - nosetests --with-xunit --with-coverage --cover-package=project test_users.py
  #Armazenando arquivo XML gerado dos testes para verificação
  artifacts:
    #Sempre irá executar esse artifact
    when: always
    #O path de armazenamento
    paths:
      - nosetests.xml
    #Rodando um Junit no teste
    reports:
      junit: nosetests.xml

#Realizando o build da imagem
build:
  stage: build
  dependencies:
    - teste-app
  services:
      - docker:dind
  script:
      - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
      - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} .
      - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}

deploy_homolog:
  stage: deploy
  dependencies:
    - build
  image: alpine
  script:
      - apk update && apk add --no-cache curl
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
      # Criando uma pasta para alocar a variável criada
      - mkdir -p $HOME/.kube
      # Salvando o conteúdo da variável em um arquivo dentro da pasta criada
      - echo -n ${kubeconfig} | base64 -d > $HOME/.kube/config
      - kubectl set image deployment/web simplepythonflask=${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} -n homolog
      - kubectl get pods -n homolog
  # Pipeline rodando no gilab e não na infra, como subimos um Runner, temos de apontar uma tag para ele.
  # Temos um Step para fazer deploy, teoaricamente, após o Build
  tags:
      - cicd-runner

#Incluindo teste SAST (Static Application Security Test) na pipeline, a mesma utilziada no Jenkins, porém, jenkins utilizou o Sonarqube
include:
  - template: Jobs/SAST.gitlab-ci.yml

spotbugs-sast:
  variables:
    FAIL_NEVER: 1